import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({
	subsets: ['latin'],
	variable: '--font-inter',
});

export const metadata = {
	title: 'Clock App',
	description: 'Generated by create next app',
	author: 'Dawid Keyser',
	viewport: 'width=device-width, initial-scale=1.0',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`dark font-sans ${inter.variable}`}>{children}</body>
		</html>
	);
}
